# Generated by Django 2.2.7 on 2019-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('sf_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=250)),
                ('website', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('unqualified', models.BooleanField(default=False)),
                ('cage_code', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
