# Generated by Django 2.2.7 on 2019-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191125_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sam_checked',
            field=models.BooleanField(default=False),
        ),
    ]
