# Generated by Django 2.2.7 on 2019-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_sam_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sf_updated',
            field=models.BooleanField(default=False),
        ),
    ]
