# Generated by Django 2.2.7 on 2020-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_sf_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='usa_spending_updated',
            field=models.BooleanField(default=False),
        ),
    ]
