# Generated by Django 2.2.7 on 2020-02-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_usa_spending_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='duns_number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
